version: "3.8"

services:
  lief-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lief-dev
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: python main.py
